version: '3'

services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=2020
      - MONGODB_CNN=mongodb://mongo:28017/test
    ports:
      - "2020:2020"
  mongo:
    image: mongo
    ports:
      - "28017:28017"